apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: homework
data:
 default.conf: |
   server {
    listen       8000;
    listen  [::]:8000;
    server_name  localhost;
    #access_log  /var/log/nginx/host.access.log  main;
    location / {
      root /homework;
      index index.html; #костыль, чтобы отображалось содержимое директории, даже если в ней есть файл index.html
      charset   utf-8;
    }
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/;
      }
    }