apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-exporter-sm
  namespace: prometheus
  labels:
    release: prometheus-stack
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: nginx
  endpoints:
    - port: nginx-exporter-port
      scheme: http