{{-  range .Values.configmap  }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{  .metadata.name  }}
  namespace: {{  .metadata.namespace  }}
data:
  {{-  toYaml .data  | nindent 4  }}
---
{{-  end  }}