{{-  range .Values.deployment  }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{  .metadata.name  }}
  namespace: {{  .metadata.namespace  }}
  labels:
    app: {{  .metadata.name  }}
spec:
  replicas: {{  .spec.replicas  }}
  selector:
    matchLabels:
      app: {{  .metadata.name  }}
  {{- if .spec.strategy  }}
  strategy:
    type: {{  .spec.strategy.type  }}
    {{-  if eq .spec.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{  .spec.strategy.rollingUpdate.maxUnavailable  }}
    {{-  end }}
  {{-  end  }}
  template:
    metadata:
      labels:
        app: {{  .metadata.name  }}
    spec:
    {{-  with .spec.template.spec  }}
      {{- if .serviceAccount  }}
      serviceAccount: {{  .serviceAccount  }}
      {{-  end  }}
      {{-  if .nodeSelector  }}
      nodeSelector:
           {{-  toYaml .nodeSelector | nindent 8  }}
      {{-  end  }}
      {{-  if .initContainers  }}
      initContainers:
      {{-  toYaml .initContainers | nindent 8  }}
      {{-  end  }}
      {{-  end  }}
      {{-  with .spec.template.spec.containers  }}
      containers:
      {{-  range .  }}
      - name: {{  .name  }}
        image: "{{  .image  }}{{- if .tag  }}:{{ .tag  }}{{- end  }}"
        ports:
        {{-  range .ports  }}
        - containerPort: {{  .containerPort  }}
        {{-  end  }}
        {{-  if and (.readinessProbe) (.readinessProbe.enabled)  }}
        readinessProbe:
        {{- if .readinessProbe.httpGet  }}
          httpGet:
        {{-  toYaml .readinessProbe.httpGet | nindent 12  }}
        {{- end  }}
        {{-  end  }}
        {{-  if and (.livenessProbe ) (.livenessProbe.enabled) }}
        livenessProbe:
        {{-  toYaml .livenessProbe | nindent 10  }}
        {{-  end  }}
        {{-  if .volumeMounts  }}
        volumeMounts:
        {{-  range .volumeMounts  }}
        - name: {{  .name  }}
          mountPath: {{  .mountPath  }}
        {{-  end  }}
        {{-  end  }}
        {{-  if .lifecycle  }}
        lifecycle:
        {{-  toYaml .lifecycle | nindent 10  }}
        {{-  end  }}
      {{- end }}
      {{- end }}
      {{-  with .spec.template.spec.volumes  }}
      volumes:
      {{-  toYaml . | nindent 6  }}
      {{- end }}
---
{{-  end  }}