{{- range .Values.ingress  }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{  .metadata.name  }}
  namespace: {{  .metadata.namespace  }}
spec:
  ingressClassName: {{  .spec.ingressClassName  }}
  rules:
  {{- .spec.rules | toYaml | nindent 2  }}
---
{{- end  }}