{{- range .Values.storageClass  }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{  .metadata.name  }}
  namespace: {{  .metadata.namespace  }}
provisioner: {{  .provisioner  }}
reclaimPolicy: {{  .reclaimPolicy  }}
volumeBindingMode: {{  .volumeBindingMode  }}
---
{{- end  }}